# Generated by Django 4.2 on 2023-06-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('hp', models.IntegerField(null=True)),
                ('types', models.JSONField(max_length=255, null=True)),
                ('abilities', models.CharField(max_length=255, null=True)),
                ('weaknesses', models.JSONField(max_length=255, null=True)),
                ('resistances', models.CharField(max_length=255, null=True)),
                ('convertedRetreatCost', models.CharField(max_length=255, null=True)),
                ('artist', models.CharField(max_length=255, null=True)),
                ('rarity', models.CharField(max_length=255, null=True)),
                ('flavorText', models.CharField(max_length=400, null=True)),
                ('small_images', models.JSONField(max_length=255, null=True)),
                ('big_images', models.JSONField(max_length=255, null=True)),
            ],
        ),
    ]
